#The print command can be used to define text to be produced in the above syntax: within the quotes of the brackets; and this command is used to present the user with a prompt explaining purposes of the program: the header.
print ("Hello user.")
print ("\nThis program is designed to use the 'print' operation within Python 3 in order to create the initials CDL as specified by the requirements of the module COMP 1036 within Leeds University (c. 2013)\n")
#The input command in Python 3 writes the parameters of its contents as if it were being written directly into the interpreter. Given that the contents are a string (using \n for text wrapping) and not any such operation all Python writes is that such string.  
input ("Press the Enter key to continue.")
#Defines HASHTAG as '#'
H = HASHTAG = ("#")
#Defines PERIOD as '.'
P = PERIOD = (".")
#Defines HYPHEN as '-'
HY = HYPHEN = ("-")
#Defines VERTBAR as '|'
V = VERTBAR = ("|")
#Defines SPACE as ' '
S = SPACE = (" ")
#Defines COMMA as "'"
C = COMMA = ("'")
print ("")
print (PERIOD+(HYPHEN*16)+PERIOD+(SPACE*2)+PERIOD+(HYPHEN*17)+PERIOD+(SPACE*2)+PERIOD+(HYPHEN*18)+PERIOD+SPACE)
print (VERTBAR+SPACE+PERIOD+(HYPHEN*14)+PERIOD+SPACE+(VERTBAR*2)+SPACE+PERIOD+(HYPHEN*15)+PERIOD+SPACE+(VERTBAR*2)+SPACE+PERIOD+(HYPHEN*14)+PERIOD+SPACE+VERTBAR)
print (VERTBAR+SPACE+VERTBAR+(SPACE*5)+(H*6)+(SPACE*3)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*2)+(HASHTAG*8)+(SPACE*5)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*3)+(HASHTAG*5)+(SPACE*6)+VERTBAR+SPACE+VERTBAR)
print (VERTBAR+SPACE+VERTBAR+(SPACE*3)+(HASHTAG*2)+SPACE+(HASHTAG*3)+(SPACE*2)+HASHTAG+(SPACE*2)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+SPACE+(HASHTAG*2)+(SPACE*3)+(HASHTAG*3)+SPACE+(HASHTAG*2)+(SPACE*3)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*2)+(HASHTAG*2)+(SPACE*3)+(HASHTAG*2)+(SPACE*5)+VERTBAR+SPACE+VERTBAR)
print (VERTBAR+SPACE+VERTBAR+(SPACE*2)+HASHTAG+SPACE+(HASHTAG*2)+(SPACE*3)+(HASHTAG*3)+(SPACE*2)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*3)+HASHTAG+SPACE+HASHTAG+(SPACE*3)+(HASHTAG*2)+SPACE+HASHTAG+(SPACE*2)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*3)+HASHTAG+SPACE+HASHTAG+(SPACE*2)+(SPACE*6)+VERTBAR+SPACE+VERTBAR)
print (VERTBAR+SPACE+VERTBAR+(SPACE*2)+HASHTAG+SPACE+HASHTAG+(SPACE*9)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*3)+HASHTAG+SPACE+HASHTAG+(SPACE*4)+HASHTAG+SPACE+HASHTAG+(SPACE*2)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*4)+HASHTAG+SPACE+HASHTAG+(SPACE*3)+HASHTAG+(SPACE*3)+VERTBAR+SPACE+VERTBAR)
print (VERTBAR+SPACE+VERTBAR+(SPACE*2)+HASHTAG+SPACE+(HASHTAG*8)+(SPACE*2)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*2)+(HASHTAG*2)+SPACE+(HASHTAG*6)+SPACE+HASHTAG+(SPACE*2)+VERTBAR+SPACE+VERTBAR+VERTBAR+SPACE+VERTBAR+(SPACE*3)+(HASHTAG*2)+SPACE+(HASHTAG*4)+SPACE+HASHTAG+(SPACE*2)+VERTBAR+SPACE+VERTBAR)
print (VERTBAR+SPACE+VERTBAR+(SPACE*3)+(HASHTAG*9)+(SPACE*2)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+SPACE+(HASHTAG*11)+(SPACE*3)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*2)+(HASHTAG*10)+(SPACE*2)+VERTBAR+SPACE+VERTBAR)
print (VERTBAR+SPACE+VERTBAR+(SPACE*14)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*15)+VERTBAR+SPACE+(VERTBAR*2)+SPACE+VERTBAR+(SPACE*14)+VERTBAR+SPACE+VERTBAR)
print (VERTBAR+SPACE+COMMA+(HYPHEN*14)+COMMA+SPACE+(VERTBAR*2)+SPACE+COMMA+(HYPHEN*14)+COMMA+(SPACE*2)+(VERTBAR*2)+SPACE+COMMA+(HYPHEN*14)+COMMA+SPACE+VERTBAR)
print (SPACE+COMMA+(HYPHEN*16)+COMMA+(SPACE*2)+COMMA+(HYPHEN*16)+COMMA+(SPACE*3)+COMMA+(HYPHEN*16)+COMMA+SPACE)
print ("My name is Callum Dempsey Leach")
# Uses the definitions and the print command to write strings, on seperate lines as governed by their formula

